all:
  hosts:
    kafka-server-1:
      ansible_host: 93.77.178.78
    kafka-server-2:
      ansible_host: 62.84.117.39
    kafka-server-3:
      ansible_host: 93.77.191.9
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_user: ubuntu
