all:
  hosts:
    kafka-server-1:
      ansible_host: 158.160.41.251
      node_id: 1
    kafka-server-2:
      ansible_host: 158.160.50.84
      node_id: 2
    kafka-server-3:
      ansible_host: 158.160.49.225
      node_id: 3
    akhq-server:
      ansible_host: 93.77.186.124
  children:
    kafka_brokers:
      hosts:
        kafka-server-1: {}
        kafka-server-2: {}
        kafka-server-3: {}
    monitoring:
      hosts:
        akhq-server: {}
